### ISSUE TITLE
Add me as Contributor

### ISSUE THREAD

**Issue by ahmedkmadani** [mohammed-A-yousif/quran_app_student#1]
Hello Mo, please add me here as Contributor too so I can do the same as in the teacher app.

Thanks

**Comment by ahmedkmadani** [comment]
Thanks @mohammed-A-yousif  I have just push the code take a loot at it , and I cant reach you out in your whatsaap phone number

**Comment by mohammed-A-yousif** [comment]
My phone died ☹️, so reach me at 0967523087

**Comment by ahmedkmadani** [comment]
Oh sorry bro okay cool no worries
